USE [master]
GO

/****** Object:  Database [ProjectAntBIDW]    Script Date: 6/03/2020 12:59:47 PM ******/
CREATE DATABASE [ProjectAntBIDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjectAntBIDW', FILENAME = N'D:\RDSDBDATA\DATA\ProjectAntBIDW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'ProjectAntBIDW_log', FILENAME = N'D:\RDSDBDATA\DATA\ProjectAntBIDW_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjectAntBIDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjectAntBIDW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjectAntBIDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjectAntBIDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProjectAntBIDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjectAntBIDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET RECOVERY FULL 
GO

ALTER DATABASE [ProjectAntBIDW] SET  MULTI_USER 
GO

ALTER DATABASE [ProjectAntBIDW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjectAntBIDW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjectAntBIDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjectAntBIDW] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ProjectAntBIDW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProjectAntBIDW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProjectAntBIDW] SET  READ_WRITE 
GO


